services:
  reverse_proxy:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/ssl
    networks:
      - frontend
      - backend

  web:
    image: nginx:alpine
    volumes:
      - ./web:/usr/share/nginx/html
    networks:
      - backend

  web1:
    image: nginx:alpine
    volumes:
      - ./web1:/usr/share/nginx/html
    networks:
      - backend

  web2:
    image: nginx:alpine
    volumes:
      - ./web2:/usr/share/nginx/html
    networks:
      - backend

  web3:
    image: nginx:alpine
    volumes:
      - ./web3:/usr/share/nginx/html
    networks:
      - backend

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
